{
 "title": "HAProxy / Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(haproxy_process_start_time_seconds, instance)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(haproxy_process_start_time_seconds, job)"
   },
   {
    "name": "backend",
    "label": "backend",
    "query": "label_values(haproxy_backend_status, proxy)"
   },
   {
    "name": "server",
    "label": "server",
    "query": "label_values(haproxy_server_status, server)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Response",
   "type": "graph",
   "description": "HTTP responses per second. There will be no data for servers using tcp mode.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_http_responses_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}:{{code}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "graph",
   "description": "Attempted connections per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "connps" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_attempts_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Bytes in/out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_bytes_in_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}:{{server}}:in",
     "refID": "A"
    },
    {
     "expr": "rate(haproxy_server_bytes_out_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}:{{server}}:out",
     "refID": "B"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "HTTP Response",
   "type": "graph",
   "description": "Response errors per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errps" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_response_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "graph",
   "description": "Connection errors per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errps" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_connection_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "graph",
   "description": "Internal errors per second",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errps" } },
   "targets": [
    {
     "expr": "rate(haproxy_server_internal_errors_total{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{proxy}}",
     "refID": "A"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Average duration",
   "type": "graph",
   "description": "Average duration for last 1024 succesful connections",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "haproxy_server_queue_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:avg queue time",
     "refID": "A"
    },
    {
     "expr": "haproxy_server_connect_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:avg connect time",
     "refID": "B"
    },
    {
     "expr": "haproxy_server_response_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:avg response time",
     "refID": "C"
    },
    {
     "expr": "haproxy_server_total_time_average_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:avg total time",
     "refID": "D"
    }
   ]
  },
  {
   "title": "Max duration",
   "type": "graph",
   "description": "Max duration for last 1024 succesful connections",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "haproxy_server_max_queue_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:max queue time",
     "refID": "A"
    },
    {
     "expr": "haproxy_server_max_connect_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:max connect time",
     "refID": "B"
    },
    {
     "expr": "haproxy_server_max_response_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:max response time",
     "refID": "C"
    },
    {
     "expr": "haproxy_server_max_total_time_seconds{instance=~\"$instance\",job=~\"$job\",proxy=~\"$backend\",server=~\"$server\"}",
     "legendFormat": "{{proxy}}:max total time",
     "refID": "D"
    }
   ]
  }
 ]
}