on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    container:
      image: "golang"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Install mixtool"
        id: "install-mixtool"
        run: "go install github.com/monitoring-mixins/mixtool/cmd/mixtool@main"

      - name: "Run mixtool"
        id: "run-mixtool"
        run: "mixtool lint mixin.libsonnet"
